config/routes.rb
Socialum::Application.routes.draw do
  resources :overview, :only => [:index]

  # Raiz de la app
  root :to => 'baxs#index'

  # Recursos anidados: arribos y descargas
  resources :baxs, :only => [:index, :show] do
    resources :bax_gabarras, :only => [:index]
    get '/bax_gabarras/:gabarra_id' => 'bax_gabarras#show', 
      :constraints => { :gabarra_id => /[A-Z]{2,4}-\d{2,4}/ }, 
      :as => :bax_gabarra

    resources :arribos_bauxitas, :except => [:new, :edit] do
      resources :descargas, :except => [:new, :edit]
    end
  end

  # Recursos de autenticacion
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  # Plantilla de recursos
  match '/:controller(/:action(/:id))'
end

app/views/shared/_devise_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('devise.sessions.link'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('devise.registrations.link'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t('devise.passwords.link'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('devise.confirmations.link'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && controller_name != 'unlocks' %>
  <%= link_to t('devise.unlocks.link'), new_unlock_path(resource_name) %><br />
<% end -%>

app/views/shared/_foot.html.haml
/ Le javascript
= javascript_include_tag 'application'
= yield(:javascripts)

app/views/shared/_head.html.haml
!!!
%html{:lang => 'es'}
  %head
    %meta{:charset => 'utf-8'}
    %title= "#{yield(:titulo) || controller.action_name} | #{Socialum::Application.config.name} – #{Socialum::Application.config.company}"
    %meta{:content => Socialum::Application.config.description, :name => 'description'}
    %meta{:content => Socialum::Application.config.author, :name => 'author'}
    = csrf_meta_tags

    = yield(:head)

    / Le styles
    = stylesheet_link_tag 'application'
    = yield(:stylesheets)

    / Le HTML5 Shiv, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag 'html5.shiv'

    / Le fav and touch icons
    = favicon_link_tag

app/views/shared/_menu.html.haml
- areas.each do |area|
  %span.area-name= area['nombre']

  %ul.area
    - area['procesos'].each do |proceso|
      %li{:class => activo(proceso['controller'])}
        %a{:href => "/#{proceso['controller']}"}
          %i{:class => proceso['icono']}
          = proceso['descripcion']