config/routes.rb
Socialum::Application.routes.draw do
  resources :overview, :only => [:index]

  # Raiz de la app
  root :to => 'baxs#index'

  # Recursos anidados: arribos y descargas
  resources :baxs, :only => [:index, :show] do
    resources :bax_gabarras, :only => [:index]
    get '/bax_gabarras/:gabarra_id' => 'bax_gabarras#show', 
      :constraints => { :gabarra_id => /[A-Z]{2,4}-\d{2,4}/ }, 
      :as => :bax_gabarra

    resources :arribos_bauxitas, :except => [:new, :edit] do
      resources :descargas, :except => [:new, :edit]
    end
  end

  # Recursos de autenticacion
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  # Plantilla de recursos
  match '/:controller(/:action(/:id))'
end

app/models/bax.rb
class Bax < ActiveRecord::Base
  # Por no cumplir con la convención de Rails,
  # se definen la entidad y clave primaria de BD
  self.table_name  = :vw_bax
  self.primary_key = :id

  # Relación con otros modelos
  belongs_to :remolcador, :foreign_key => :remolcador_id
  belongs_to :empresa_maritima, :foreign_key => :empresa_maritima_id
  has_one    :arribo_bauxita, :foreign_key => :bax_id
  has_many   :bax_gabarras
  has_many   :gabarras, :through => :bax_gabarras
  has_many   :descarga_bauxitas, :through => :arribo_bauxita

  scope :embarques, includes(:remolcador, :empresa_maritima, { :arribo_bauxita => [:descarga_bauxitas] }) 
    
  # Se define como de solo lectura por ser una vista de BD
  protected
    def readonly? 
      true
    end
end

app/controllers/baxs_controller.rb
class BaxsController < ApplicationController
  before_filter :authenticate_user! # Autentica cada usuario contra LDAP antes de ejecutar cualquier controller
  respond_to :html, :json
  
  def index
    @baxes = Bax.embarques.all
    respond_with @baxes
  end

  def show
    @bax = Bax.find(params[:id])
    respond_with @bax
  end
end

app/helpers/baxs_helper.rb
module BaxsHelper
  def formato_bax bax_id
    bax_id.gsub(/-/, '/')
  end

  def avance bax
    progreso = bax.arribo_bauxita.descarga_bauxitas.progreso * 100 / bax.carga_transportar
    number_to_percentage(progreso, :precision => 2)
  end

  def eta bax
    (bax.fecha_hora_zarpe.to_datetime + bax.remolcador.tiempo_mina_planta.to_i.hours).to_s.to_datetime
  end
end

app/views/baxs/index.html.haml
- titulo 'Arribos de material'
- content_for :stylesheets, stylesheet_link_tag(controller.controller_name)
- content_for :filtros do
  %li 
    %a{:href => '#', :data => {:reportado => 'todos'}} Todos los BAX
  %li 
    %a{:href => '#', :data => {:reportado => 'reportado'}} BAX reportados
  %li 
    %a{:href => '#', :data => {:reportado => 'no-reportado'}} BAX no reportados

- @baxes.each do |bax|
  %article.bax{ :id => "bax-#{bax.id}", :name => "bax-#{bax.id}", 'data-bax-reportado' => bax.arribo_bauxita ? 'true' : 'false'}
    %header.row-fluid
      %h2
        =h "BAX: #{formato_bax(bax.id)}"

    .bax-data.row-fluid
      .span4
        %h6 remolcador
        %p.data-desc= h bax.remolcador.nombre_rem.titleize
        %h6 Empresa
        %p.data-desc= h bax.empresa_maritima.nombre_emp
        %h6 Capitán
        %p.data-desc= h bax.nombre_capitan.titleize

      .span4
        %h6 Zarpe el Jobal
        %time.data-desc{ :datetime => bax.fecha_hora_zarpe.to_datetime }= l bax.fecha_hora_zarpe.to_datetime, :format => :fecha_hora_mil

        - if bax.arribo_bauxita
          %h6 Arribo Matanzas (M201)
          %time.data-desc{ :id => "arribo-bax-#{bax.id}", :datetime => bax.arribo_bauxita.fecha_hora_arribo_bauxita.to_datetime, 'data-eta' => eta(bax) }= l bax.arribo_bauxita.fecha_hora_arribo_bauxita.to_datetime, :format => :fecha_hora_mil

        - else
          %h6 ETA Matanzas (M201)
          %time.data-desc{ :id => "eta-arribo-bax-#{bax.id}", :datetime => eta(bax), 'data-eta' => eta(bax) }= l (bax.fecha_hora_zarpe.to_datetime + bax.remolcador.tiempo_mina_planta.to_i.hours).to_s.to_datetime, :format => :fecha_hora_mil

        %h6 Tonelaje
        %p.data-desc= h "#{number_with_delimiter(bax.carga_transportar, :precision => 2, :delimiter => ".", :separator => ",")} tons."

      .span4.botones
        - if bax.arribo_bauxita
          %button.btn.btn-success.btn-small.disabled{ :id => "bax-arribo-#{bax.id}", :rel => 'tooltip', :data => {'original-title' => "#{l bax.arribo_bauxita.fecha_hora_arribo_bauxita.to_datetime, :format => :fecha_hora_mil}", 'arribo-bauxita-id' => bax.arribo_bauxita.id, 'bax-id' => bax.id, :url => bax_arribos_bauxitas_path(bax.id)} } 
            %i.fa-icon-ban-circle 
            Arribo reportado

        - else              
          %button.btn.btn-primary.btn-small{ :id => "bax-arribo-#{bax.id}", 'data-bax-id' => bax.id, :data => {:type => 'report-arribo', :url => bax_arribos_bauxitas_path(bax.id), (can? :create, ArriboBauxita) ? nil : :disabled => :disabled} } 
            %i.fa-icon-bullhorn 
            Reportar arribo

        - if (can? :manage, ArriboBauxita)
          %button{:id => "delete-arribo-#{bax.id}", :class => "btn btn-danger btn-small #{bax.arribo_bauxita ? nil : 'hide'}", :data => {:url => "#{bax.arribo_bauxita ? bax_arribo_bauxita_path(bax.id, bax.arribo_bauxita.id) : nil}", 'bax-id' => bax.id, :type => 'delete-arribo'} }
            %i.fa-icon-trash
            Eliminar arribo

        %button.btn.btn-small{'data-type' => 'view-gabarras', 'data-url' => bax_bax_gabarras_path(bax.id) } 
          %i.fa-icon-th 
          = "Ver gabarras (#{bax.cant_gabarras})"

      %div{ :class => "span12 #{bax.arribo_bauxita ? nil : 'hide'}", :id => "bax-progress-bar-#{ bax.id }" }
        %h6 Progreso de descarga
        .progress.progress-striped.active
          .bar{ :style => "width:#{ bax.arribo_bauxita ? avance(bax) : '0' }", :id => "bax-descarga-#{ bax.id }", :rel => 'tooltip', :data => {'tonelaje-total' => bax.carga_transportar, :progreso => bax.arribo_bauxita.nil? ? 0 : bax.arribo_bauxita.descarga_bauxitas.progreso, 'original-title' => "#{ bax.arribo_bauxita ? avance(bax) : '0%' }"} }= h "#{bax.arribo_bauxita ? number_with_delimiter(bax.arribo_bauxita.descarga_bauxitas.progreso, :precision => 2, :delimiter => ".", :separator => ",") : '0,0' } tons."

- content_for :javascripts, javascript_include_tag(controller.controller_name)